services:
  clip-server:
    build: .
    ports:
      - "51009:51000"
    volumes:
      - clip_cache:/home/cas/.cache
      - ./config.yml:/config.yml:ro
    entrypoint: [ "sh", "-c", "cat /config.yml | python -m clip_server -i" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  clip_cache:
