services:
  clip-server:
    image: jinaai/clip-server
    ports:
      - "51009:51000"
    volumes:
      - clip_cache:/home/cas/.cache         # Docker-managed volume (safe!)
      - ./my.yml:/my.yml:ro                 # Read-only mount of your config file
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    entrypoint: [ "sh", "-c", "cat /my.yml | python -m clip_server -i" ]
    stdin_open: true
    tty: true

volumes:
  clip_cache: