services:
  clip-server:
    image: jinaai/clip-server
    ports:
      - "51009:51000"
    volumes:
      - clip_cache:/home/cas/.cache
      - ./my.yml:/my.yml:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    entrypoint: [ "sh", "/entrypoint.sh" ]
    stdin_open: true
    tty: true

volumes:
  clip_cache:
