[project]
name = "autipdf-clip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "clip-client>=0.8.3",
    "elasticsearch>=8.17.2",
    "fastapi>=0.115.11",
    "setuptools>=76.0.0",
]
